stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/ref
        - cp -frv ./include/ref $INC_PATH
        - rm -f $INC_PATH/stub/ref*
        - cp -frv ./include/stub $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libref.a $DBG_PATH
        - cp -fv debug/librefstub.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libref.a $REL_PATH
        - cp -fv release/librefstub.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_ref $UT_PATH

        - mkdir -p $BIN_PATH
        - cp -fv release/refview $BIN_PATH
        - cp -fv release/loadref $BIN_PATH
    only:
        - master

mkt:
    stage: trigger
    script:
        - curl -X POST -F token=e7c53a9167112714608cf4602c6741 -F ref=master $GITLAB_URL/api/v4/projects/18/trigger/pipeline
    only:
        - master
